import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar2, Navbar2Defaults } from "./(component)/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar2 {...Navbar2Defaults}/>
        {children}
        </body>
    </html>
  );
}
